services: # Define the containers/services in your application
  backend: # First service - Rust backend
    build: # Build configuration
      context: ./backend
      dockerfile: Dockerfile
    ports: # Port mapping
      - "8000:8000" # Host port:Container port
    environment: # Environment variables
      - RUST_LOG=info
    networks: # Network configuration
      - app-network # Connect to the defined network

  frontend: # Second service - Next.js frontend
    build:
      context: ./frontend # Frontend project directory
      dockerfile: Dockerfile # Frontend Dockerfile
    ports:
      - "3000:3000" # Expose frontend port
    depends_on: # Ensure backend starts before frontend
      - backend
    networks:
      - app-network # Same network as backend

networks: # Network definition
  app-network: # Custom network name
    driver: bridge # Standard Docker network driver
